In [ ]:
import pandas as pd

In [ ]:
df= pd.read_csv('/content/OnlineRetail.csv',encoding='ISO-8859-1')

In [ ]:
print(df.head(3))

  InvoiceNo StockCode                         Description  Quantity  \
0    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                 WHITE METAL LANTERN         6
2    536365    84406B      CREAM CUPID HEARTS COAT HANGER         8

        InvoiceDate  UnitPrice  CustomerID         Country
0  01-12-2010 08:26       2.55     17850.0  United Kingdom
1  01-12-2010 08:26       3.39     17850.0  United Kingdom
2  01-12-2010 08:26       2.75     17850.0  United Kingdom

In [ ]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,09-12-2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,09-12-2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,09-12-2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,09-12-2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,09-12-2011 12:50,4.95,12680.0,France

In [ ]:
df.shape

(541909, 8)

In [ ]:
df.isna()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
541904,False,False,False,False,False,False,False,False
541905,False,False,False,False,False,False,False,False
541906,False,False,False,False,False,False,False,False
541907,False,False,False,False,False,False,False,False
541908,False,False,False,False,False,False,False,False

In [ ]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [ ]:
df.dropna(subset=['CustomerID'],inplace=True)

In [ ]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,09-12-2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,09-12-2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,09-12-2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,09-12-2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,09-12-2011 12:50,4.95,12680.0,France

In [ ]:
df.shape

(406829, 8)

In [ ]:
return_count = (df['Quantity'] < 0).sum()
print(return_count)

8905

In [ ]:
df = df[df['Quantity'] > 0]

In [ ]:
df.shape

(397924, 8)

In [ ]:
df.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [ ]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,09-12-2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,09-12-2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,09-12-2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,09-12-2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,09-12-2011 12:50,4.95,12680.0,France

In [ ]:
import datetime as dt

In [ ]:
df.loc[:,'InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], dayfirst=True)
df.loc[:,'CustomerID'] = df['CustomerID'].astype(int)

In [ ]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [ ]:
return_zero = (df['Quantity'] == 0).sum()
print(return_zero)

0

In [ ]:
df.loc[:,'Revenue'] = df['Quantity'] * df['UnitPrice']

In [ ]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85

In [ ]:
rfm_df=df.dropna(subset=['CustomerID'])

In [ ]:
rfm_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85

In [ ]:
admin_items = ['DOTCOM POSTAGE', 'AMAZON FEE', 'POSTAGE', 'Bank Charges', 'Manual', 'Adjust bad debt']
rfm_df = rfm_df[~rfm_df['Description'].isin(admin_items)]

In [ ]:
rfm_df.shape

(396507, 9)

In [ ]:
print("Unique Customers:", rfm_df['CustomerID'].nunique())

Unique Customers: 4335

In [ ]:
snapshot_date = rfm_df['InvoiceDate'].max() + dt.timedelta(days=1)

In [ ]:
rfm = rfm_df.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (snapshot_date - x.max()).days, # Recency
    'InvoiceNo': 'nunique',                                  # Frequency
    'Revenue': 'sum'                                         # Monetary
})

In [ ]:
rfm.columns = ['Recency', 'Frequency', 'Monetary']

In [ ]:
rfm

            Recency  Frequency  Monetary
CustomerID
12346.0         326          1  77183.60
12347.0           2          7   4310.00
12348.0          75          4   1437.24
12349.0          19          1   1457.55
12350.0         310          1    294.40
...             ...        ...       ...
18280.0         278          1    180.60
18281.0         181          1     80.82
18282.0           8          2    178.05
18283.0           4         16   2088.93
18287.0          43          3   1837.28

[4335 rows x 3 columns]

In [ ]:
print(f"Data starts: {rfm_df['InvoiceDate'].min()}")
print(f"Data ends:   {rfm_df['InvoiceDate'].max()}")

Data starts: 2010-12-01 08:26:00
Data ends:   2011-12-09 12:50:00

In [ ]:
r_labels = range(5, 0, -1) # 5 is most recent, 1 is least recent
f_labels = range(1, 6)    # 5 is highest frequency
m_labels = range(1, 6)    # 5 is highest spend

In [ ]:
# 2. Assign scores to 5 groups
rfm['R'] = pd.qcut(rfm['Recency'], q=5, labels=r_labels)
rfm['F'] = pd.qcut(rfm['Frequency'].rank(method='first'), q=5, labels=f_labels)
rfm['M'] = pd.qcut(rfm['Monetary'], q=5, labels=m_labels)

In [ ]:
# 3. Concatenate scores into a single string for segmenting
rfm['RFM_Group'] = rfm.R.astype(str) + rfm.F.astype(str) + rfm.M.astype(str)

In [ ]:
# 4. Calculate a total RFM Score (numeric sum)
rfm['RFM_Score'] = rfm[['R', 'F', 'M']].sum(axis=1)

In [ ]:
rfm

            Recency  Frequency  Monetary  R  F  M RFM_Group  RFM_Score
CustomerID
12346.0         326          1  77183.60  1  1  5       115          7
12347.0           2          7   4310.00  5  5  5       555         15
12348.0          75          4   1437.24  2  4  4       244         10
12349.0          19          1   1457.55  4  1  4       414          9
12350.0         310          1    294.40  1  1  2       112          4
...             ...        ...       ... .. .. ..       ...        ...
18280.0         278          1    180.60  1  2  1       121          4
18281.0         181          1     80.82  1  2  1       121          4
18282.0           8          2    178.05  5  3  1       531          9
18283.0           4         16   2088.93  5  5  5       555         15
18287.0          43          3   1837.28  3  4  4       344         11

[4335 rows x 8 columns]

In [ ]:
def segment_me(df):
    if df['RFM_Score'] >= 14:
        return 'Champions'
    elif (df['RFM_Score'] >= 11) and (df['RFM_Score'] < 14):
        return 'Loyal Customers'
    elif (df['RFM_Score'] >= 8) and (df['RFM_Score'] < 11):
        return 'Potential Loyalist'
    elif (df['RFM_Score'] >= 5) and (df['RFM_Score'] < 8):
        return 'At Risk / Hibernating'
    else:
        return 'Lost'

rfm['Segment'] = rfm.apply(segment_me, axis=1)

In [ ]:
segment_counts = rfm['Segment'].value_counts()
print(segment_counts)

Segment
At Risk / Hibernating    1141
Potential Loyalist       1056
Loyal Customers           949
Champions                 650
Lost                      539
Name: count, dtype: int64

In [ ]:
import plotly.express as px
import plotly.io as pio

# IMPORTANT FIX
pio.renderers.default = 'colab'

# Prepare data
rfm_stats = rfm.groupby('Segment').agg({
    'Recency': 'mean',
    'Frequency': 'mean',
    'Monetary': ['mean', 'count']
}).round(1)

rfm_stats.columns = ['Recency_Mean', 'Frequency_Mean', 'Monetary_Mean', 'Count']
rfm_stats = rfm_stats.reset_index()

# Plot
fig = px.treemap(
    rfm_stats,
    path=['Segment'],
    values='Count',
    color='Monetary_Mean',
    title='RFM Customer Segments'
)

fig.show()

In [ ]:
rfm

,Recency,Frequency,Monetary,R,F,M,RFM_Group,RFM_Score,Segment
CustomerID,,,,,,,,,
12346.0,326,1,77183.60,1,1,5,115,7,At Risk / Hibernating
12347.0,2,7,4310.00,5,5,5,555,15,Champions
12348.0,75,4,1437.24,2,4,4,244,10,Potential Loyalist
12349.0,19,1,1457.55,4,1,4,414,9,Potential Loyalist
12350.0,310,1,294.40,1,1,2,112,4,Lost
...,...,...,...,...,...,...,...,...,...
18280.0,278,1,180.60,1,2,1,121,4,Lost
18281.0,181,1,80.82,1,2,1,121,4,Lost
18282.0,8,2,178.05,5,3,1,531,9,Potential Loyalist
18283.0,4,16,2088.93,5,5,5,555,15,Champions
18287.0,43,3,1837.28,3,4,4,344,11,Loyal Customers

In [ ]:
rfm.to_csv('rfm_dataset.csv', index=False)